#!/usr/bin/bash

pathDir=$1
PDF_name=`basename $pathDir`

# for entry in $pathDir/*
# do
#   subDir=`basename $entry`
#   if [ -d $entry ] && [ ${subDir:0:-3} = $PDF_name ];
#   then
#     # java test "$entry/field_name.txt" "$entry/user_value.txt"
#     python ObjectHandle.py --mode '1' --user_value "$entry/user_value.txt" --input_template "$entry/template.json" --user_json "$entry/user.json"
#     python ImgGen.py --template "$entry/user.json" --output "$entry.jpg" --input "$(echo $entry/*.jpg)"
#   fi
# done
python GetPdf.py --directory "$pathDir" --output "$pathDir/$PDF_name.pdf"


